### ISSUE TITLE
Filament_Path_xN.stl has 6 non-mainfold edges

### ISSUE THREAD

**Issue by relder** [Enraged-Rabbit-Community/ERCF_v2#79]
Both prusaslicer and orca slicer complain that https://github.com/Enraged-Rabbit-Community/ERCF_v2/blob/master/Stls/Filament_Blocks/Filament_Path_xN.stl has 6 non-mainfold edges and recommends repair.

**Comment by MissileLaunchSystem** [comment]
It's a known issue with the built-in supports. If you fix the manifold edges, it makes the supports print as a solid piece instead of hollow, which uses (read: wastes) about a gram more plastic. I'll ask the designer to take a look again.

**Comment by gneu42** [comment]
Yes, this know since the very begining. I think it is a fusion 360 bug.
Also, make sure to have the detect thin wall ticked, or you may have no supports.

Just ignore it, as mentioned in the readme file from triple decky github: https://github.com/gneu42/Triple-Decky?tab=readme-ov-file#printing-tips

![Capture2](https://github.com/Enraged-Rabbit-Community/ERCF_v2/assets/59416685/a4dab30c-5be1-44ae-b538-1437c7852824)
